In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [61]:
X, y,expected_w = make_regression(n_samples = 1000,n_features=3, coef=True)
expected_w = np.insert(expected_w,0,0)
X = np.insert(X,0,np.ones(1000),axis=1)
print(X.shape,y.shape,expected_w)
X[:6,:]

(1000, 4) (1000,) [ 0.         23.91073238 64.42258745 70.45221957]


array([[ 1.        , -0.32184566,  0.21840433, -0.61583433],
       [ 1.        , -0.50469189,  1.1870829 ,  1.21019048],
       [ 1.        , -0.40427459,  0.04240531,  0.90706733],
       [ 1.        , -0.28311126, -2.49709425, -1.19391298],
       [ 1.        ,  0.28564727, -0.66061428,  0.32435738],
       [ 1.        ,  0.04283086, -0.95593841, -0.30275126]])

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.25)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((750, 4), (250, 4), (750,), (250,))

In [63]:
w = np.zeros(4)
w.shape

(4,)

In [64]:
def loss(X, y, w):

    l = (np.dot(X,w)-y)
    l = np.dot(l.T,l)
    return l/(2 * X.shape[0])

In [65]:
def gradient(X, y, w):

    dj_dw = np.dot(X,w)-y
    dj_dw = np.dot(X.T,dj_dw)
    return dj_dw/X.shape[0]

In [66]:
dj = gradient(X_train,y_train,w)
dj

array([  3.84500396, -14.24959684, -61.7568569 , -71.47796749])

In [67]:
def gradientDescent(X, y, w, alpha=0.01, iteration=1000):

      for i in range(iteration):
            dj_dw = gradient(X,y,w)
            w = w - alpha * dj_dw
            if (i%10) == 0 or i == iteration-1:
                los = loss(X,y,w)
                print(f"itration {i}, loss = {los:.2e} w = {w},")
      return w

In [68]:
updated_w = gradientDescent(X_train,y_train,w,6e-1,100)
updated_w

itration 0, loss = 8.19e+02 w = [-2.30700238  8.5497581  37.05411414 42.88678049],
itration 10, loss = 1.96e-04 w = [-4.52531117e-03  2.38942733e+01  6.44129278e+01  7.04441207e+01],
itration 20, loss = 7.59e-11 w = [-2.68999450e-06  2.39107216e+01  6.44225827e+01  7.04522142e+01],
itration 30, loss = 3.03e-17 w = [-1.62111569e-09  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 40, loss = 1.23e-23 w = [-9.97393333e-13  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 50, loss = 4.12e-29 w = [-1.99583570e-15  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 60, loss = 3.92e-29 w = [-3.64473986e-16  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 70, loss = 3.91e-29 w = [-1.98606666e-16  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 80, loss = 3.91e-29 w = [-1.62413395e-16  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 90, loss = 3.91e-29 w = [-1.26220125e-16  2.39107324e+01  6.44225874e+01  7.04522196e+01],
itration 99, loss

array([-1.05014865e-16,  2.39107324e+01,  6.44225874e+01,  7.04522196e+01])

In [69]:
expected_w - updated_w

array([1.05014865e-16, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [70]:
def predict(X,w):
    y = np.dot(X,w)
    return y

In [71]:
def MSE(y_hat, y):

    e = (y_hat-y)
    e = np.dot(e.T,e)
    return e/(2 * X.shape[0])

In [72]:
y_hat = predict(X_test,updated_w)
MSE(y_hat,y_test)

1.0897281403892302e-29

In [73]:
for i in range(5):
  print(f"yhat[{i}] = {y_hat[i]} and y[{i}] = {y_test[i]}")

yhat[0] = 81.13128231172655 and y[0] = 81.13128231172655
yhat[1] = 26.462961579573626 and y[1] = 26.462961579573626
yhat[2] = 205.13651269837771 and y[2] = 205.13651269837774
yhat[3] = -17.072792503319047 and y[3] = -17.072792503319047
yhat[4] = -30.422586432318425 and y[4] = -30.42258643231843
